### ISSUE TITLE
ProjectProvider.reloadProject на проде ломает freemarker

### ISSUE THREAD

**Issue by QProgS** [DevelopmentOnTheEdge/be5#107]
Caused by: com.developmentontheedge.be5.base.exceptions.Be5Exception: Internal error occurred during query: tariffs.*** Selection view ***
        at com.developmentontheedge.be5.base.exceptions.Be5Exception.create(Be5Exception.java:54)
        at com.developmentontheedge.be5.base.exceptions.Be5ErrorCode.rethrow(Be5ErrorCode.java:37)
        at com.developmentontheedge.be5.base.exceptions.Be5Exception.internalInQuery(Be5Exception.java:94)
        at com.developmentontheedge.be5.base.services.impl.MetaImpl.getQueryCode(MetaImpl.java:362)
        at com.developmentontheedge.be5.query.impl.Be5QueryExecutor.getFinalSql(Be5QueryExecutor.java:213)
        at com.developmentontheedge.be5.query.impl.Be5QueryExecutor.execute(Be5QueryExecutor.java:174)
        ... 51 more
Caused by: com.developmentontheedge.be5.metadata.exception.ProjectElementException: biostore/Modules/biostore-base/Entities/tariffs/Queries/*** Selection view ***[3,76]: Project database system is not defined
        at com.developmentontheedge.be5.metadata.freemarker.FreemarkerUtils.translateException(FreemarkerUtils.java:371)
        at com.developmentontheedge.be5.metadata.freemarker.FreemarkerUtils.mergeTemplateByPath(FreemarkerUtils.java:440)
        at com.developmentontheedge.be5.metadata.freemarker.FreemarkerUtils.mergeTemplateByPath(FreemarkerUtils.java:455)
        at com.developmentontheedge.be5.metadata.model.Project.mergeTemplate(Project.java:425)
        at com.developmentontheedge.be5.metadata.model.Query.getQueryCompiled(Query.java:173)
        at com.developmentontheedge.be5.base.services.impl.MetaImpl.getQueryCode(MetaImpl.java:357)
        ... 53 more
Caused by: java.lang.Exception: Project database system is not defined
        at com.developmentontheedge.be5.metadata.freemarker.FreemarkerUtils.translateException(FreemarkerUtils.java:327)
        ... 58 more

**Comment by QProgS** [comment]
операцию убрал, добавил вместо неё ClearAllCaches
