### ISSUE TITLE
java.lang.StackOverflowError Beans.getBeanPropertyValue()

### ISSUE THREAD

**Issue by QProgS** [DevelopmentOnTheEdge/be5#28]
```
java.lang.StackOverflowError
	at com.developmentontheedge.be5.metadata.model.base.BeModelElementSupport.getValue(BeModelElementSupport.java:306)
	at com.developmentontheedge.be5.metadata.model.EntityItem.getWellKnownName(EntityItem.java:82)
	at com.developmentontheedge.be5.metadata.model.EntityItem.equals(EntityItem.java:160)
	at com.developmentontheedge.be5.metadata.model.Query.equals(Query.java:402)
	at java.util.WeakHashMap.eq(WeakHashMap.java:287)
	at java.util.WeakHashMap.get(WeakHashMap.java:401)
	at com.developmentontheedge.beans.model.ComponentFactory.getFromComponentCache(ComponentFactory.java:979)
	at com.developmentontheedge.beans.model.ComponentFactory.getModel(ComponentFactory.java:762)
	at com.developmentontheedge.beans.model.ComponentFactory.getModel(ComponentFactory.java:750)
	at com.developmentontheedge.beans.util.Beans.getBeanPropertyAccessor(Beans.java:264)
	at com.developmentontheedge.beans.util.Beans.getBeanPropertyValue(Beans.java:291)
	at com.developmentontheedge.be5.metadata.model.base.BeModelElementSupport.getValue(BeModelElementSupport.java:313)
	at com.developmentontheedge.be5.metadata.model.EntityItem.getWellKnownName(EntityItem.java:82)
	at com.developmentontheedge.be5.metadata.model.EntityItem.equals(EntityItem.java:165)
	at com.developmentontheedge.be5.metadata.model.Query.equals(Query.java:402)
	at java.util.WeakHashMap.eq(WeakHashMap.java:287)
	at java.util.WeakHashMap.get(WeakHashMap.java:401)
	at com.developmentontheedge.beans.model.ComponentFactory.getFromComponentCache(ComponentFactory.java:979)
	at com.developmentontheedge.beans.model.ComponentFactory.getModel(ComponentFactory.java:762)
	at com.developmentontheedge.beans.model.ComponentFactory.getModel(ComponentFactory.java:750)
	at com.developmentontheedge.beans.util.Beans.getBeanPropertyAccessor(Beans.java:264)
	at com.developmentontheedge.beans.util.Beans.getBeanPropertyValue(Beans.java:291)
	at com.developmentontheedge.be5.metadata.model.base.BeModelElementSupport.getValue(BeModelElementSupport.java:313)
	at com.developmentontheedge.be5.metadata.model.EntityItem.getWellKnownName(EntityItem.java:82)
	at com.developmentontheedge.be5.metadata.model.EntityItem.equals(EntityItem.java:165)
	at com.developmentontheedge.be5.metadata.model.Query.equals(Query.java:402)
	at java.util.WeakHashMap.eq(WeakHashMap.java:287)
	at java.util.WeakHashMap.get(WeakHashMap.java:401)
```

**Comment by QProgS** [comment]
исправлял пока так:
remove for prevent StackOverflowError
51e6efd8d3187e716a51306d86b13e564f5a1b69
d2127067f7a1a522750e294d6677c4cb156e0590
здесь просто добавлял тесты в meatdata и стало падать на CI и debian

fix StackOverflowError
c5469f96ae92a25e52a54cc4cb64bca4194f7a50
в egisso-be5 случайно заметил при удалении layout - из categories.yaml ломаются несколько queries
